spring:
  config:
    import: "optional:configserver:"
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/dh
  cloud:
    config:
      discovery:
        serviceId: config-service
        enabled: true
    gateway:
      default-filters:
        - TokenRelay
        - SaveSession
      routes:
        - id: checkout-service
          uri: http://localhost:8082
          predicates:
            - Path=/checkout
          filters:
            - AddRequestHeader=X-Request-from, gateway
            - AddResponseHeader=X-Response-Red, blue

server:
  port: 8085

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG

