spring:
  config:
    import: "optional:configserver:"  # Usa config-server, pero la app sigue funcionando si no está disponible.
  security:
    oauth2:
      resourceserver:
        jwt:
          issue-uri: http://localhost:8080/realms/dh
application:
  name: gateway-service  # Identificador del servicio.
cloud:
  config:
    discovery:
      serviceId: config-service  # Descubre automáticamente el servidor de configuración.
      enabled: true
  gateway:
    default-filters:
    - TokenRelay=
    routes:
      - id: checkout-service
        uri: http://localhost:8082  # Redirige las solicitudes a checkout-service.
        predicates:
          - Path=/checkout/**  # Solo aplica a rutas que comiencen con /checkout/.
        filters:
          - StripPrefix=0  # No elimina partes del path.
          - AddRequestHeader=X-Request-from, gateway  # Agrega un header a la solicitud.
          - AddResponseHeader=X-Response-Red, blue  # Agrega un header a la respuesta.
server:
  port: 8084  # El Gateway escucha en el puerto 8084.

